version: "3.9"

services:
  fastapi:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - external_api

  external_api:
    build:
      context: ./external_api
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
