version: '3.8'

services:
  jobberwoky:
    image: jobberwoky
    container_name: jobberwoky
    build:
      context: ./
    depends_on:
      - avatureexternaljobs
    ports:
      - "8080:80"
    networks:
      - my_network

  avatureexternaljobs:
    image: avatureexternaljobs
    container_name: avatureexternaljobs
    build:
      context: ./jobberwocky-extra-source-v2
    ports:
      - "8081:8080"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
